"""
auto_sticker.py — Create guild stickers from images with subject-zoom cropping.

Usage:
  !sticker              — use image from reply (or last image in channel)
  !sticker funny name   — same but override the generated name

Subject is found by locating the densest region of edges/texture in the image
(works for people, cats, dogs, objects — anything with more detail than the
background). Falls back to center-square crop if OpenCV isn't installed.
Sticker name is generated by Claude based on the image sender's display name.

Requirements (install in bot venv):
  pip install Pillow
  pip install opencv-python-headless   (optional but highly recommended)
"""

import asyncio
import base64
import io
import logging
import os
import re

import aiohttp
import discord
from discord.ext import commands

try:
    from PIL import Image as _Image
    _PIL = True
except ImportError:
    _PIL = False

try:
    import cv2 as _cv2
    import numpy as _np
    _CV2 = True
except Exception:
    _CV2 = False

try:
    from anthropic import AsyncAnthropic as _Anthropic
except ImportError:
    _Anthropic = None

log = logging.getLogger(__name__)

MODEL        = "claude-haiku-4-5-20251001"
STICKER_SIZE = 320
MAX_BYTES    = 490 * 1024
_NAME_RE     = re.compile(r"[^a-zA-Z0-9 _\-]")


def _sanitize_name(name: str) -> str:
    name = _NAME_RE.sub("", name).strip()[:30]
    return name if len(name) >= 2 else "sticker"


def _make_thumb(raw: bytes, size: int = 512) -> bytes:
    """Shrink image to at most size×size JPEG for cheap Claude vision calls."""
    img = _Image.open(io.BytesIO(raw)).convert("RGB")
    img.thumbnail((size, size), _Image.Resampling.LANCZOS)
    out = io.BytesIO()
    img.save(out, format="JPEG", quality=85)
    out.seek(0)
    return out.read()


def _media_type(raw: bytes) -> str:
    if raw[:8] == b"\x89PNG\r\n\x1a\n":
        return "image/png"
    if raw[:6] in (b"GIF87a", b"GIF89a"):
        return "image/gif"
    if raw[:4] == b"RIFF" and raw[8:12] == b"WEBP":
        return "image/webp"
    return "image/jpeg"


def _subject_crop(raw: bytes) -> "_Image.Image":
    """
    Return a PIL Image cropped around the most visually prominent subject.

    Uses Canny edge detection blurred into a density map, then finds the
    weighted centroid and estimates subject size from the spread. Falls back
    to center-square crop if OpenCV is unavailable or density is flat.
    """
    img_pil = _Image.open(io.BytesIO(raw)).convert("RGB")
    iw, ih = img_pil.size

    if _CV2:
        arr  = _np.array(img_pil)
        gray = _cv2.cvtColor(arr, _cv2.COLOR_RGB2GRAY)

        # Edge map blurred into a smooth density field
        edges   = _cv2.Canny(gray, 30, 100)
        sigma   = max(iw, ih) * 0.04
        density = _cv2.GaussianBlur(edges.astype(_np.float32), (0, 0), sigmaX=sigma)

        total = float(density.sum())
        if total > 0:
            ys, xs = _np.mgrid[0:density.shape[0], 0:density.shape[1]]
            cx = int((xs * density).sum() / total)
            cy = int((ys * density).sum() / total)

            # Subject size ≈ 2.5× std-dev of the edge density distribution
            x_std  = float(_np.sqrt(((xs - cx) ** 2 * density).sum() / total))
            y_std  = float(_np.sqrt(((ys - cy) ** 2 * density).sum() / total))
            radius = int(max(x_std, y_std) * 2.5)
            side   = max(radius * 2, min(iw, ih) // 2)
            side   = min(side, min(iw, ih))

            half   = side // 2
            left   = max(0, cx - half)
            top    = max(0, cy - half)
            right  = min(iw, left + side)
            bottom = min(ih, top + side)
            if right > iw:
                left  = max(0, iw - side)
                right = iw
            if bottom > ih:
                top    = max(0, ih - side)
                bottom = ih
            return img_pil.crop((left, top, right, bottom))

    # Fallback: center-square crop
    side = min(iw, ih)
    left = (iw - side) // 2
    top  = (ih - side) // 2
    return img_pil.crop((left, top, left + side, top + side))


def _process_image(raw: bytes) -> bytes:
    """Convert raw image bytes → 320×320 sticker PNG (or JPEG if PNG is too large)."""
    if not _PIL:
        raise RuntimeError("Pillow not installed — run: pip install Pillow")

    img = _subject_crop(raw).convert("RGB")
    img = img.resize((STICKER_SIZE, STICKER_SIZE), _Image.Resampling.LANCZOS)

    out = io.BytesIO()
    img.save(out, format="PNG", optimize=True)
    if out.tell() <= MAX_BYTES:
        out.seek(0)
        return out.read()

    # Fallback to JPEG for large images
    quality = 85
    while quality >= 40:
        out = io.BytesIO()
        img.save(out, format="JPEG", quality=quality, optimize=True)
        if out.tell() <= MAX_BYTES:
            break
        quality -= 10

    out.seek(0)
    return out.read()


class AutoStickerCog(commands.Cog, name="AutoSticker"):
    """Creates guild stickers from images with subject-zoom cropping and AI name generation."""

    def __init__(self, bot: commands.Bot):
        self.bot = bot
        api_key  = os.getenv("ANTHROPIC_API_KEY")
        self.ai  = _Anthropic(api_key=api_key) if _Anthropic and api_key else None

    def cog_load(self):
        log.info("Cog Loaded. cv2=%s Pillow=%s", _CV2, _PIL)
        if not _PIL:
            log.warning("Pillow not installed — !sticker will fail. Run: pip install Pillow")
        if not _CV2:
            log.info("opencv not installed — using center-crop fallback. Run: pip install opencv-python-headless")

    def cog_unload(self):
        log.info("Cog Unloaded.")

    # ── Image discovery ────────────────────────────────────────────────────────

    async def _find_image(self, ctx: commands.Context) -> tuple[str, str] | None:
        """
        Return (image_url, sender_display_name) or None.
        Checks: reply → command message attachments → last 20 channel messages.
        """
        def _img_url(msg: discord.Message) -> str | None:
            for att in msg.attachments:
                if att.content_type and att.content_type.startswith("image"):
                    return att.url
            for emb in msg.embeds:
                if emb.image:
                    return emb.image.url
                if emb.thumbnail:
                    return emb.thumbnail.url
            return None

        # 1. Replied-to message
        if ctx.message.reference and ctx.message.reference.resolved:
            ref = ctx.message.reference.resolved
            if isinstance(ref, discord.Message):
                url = _img_url(ref)
                if url:
                    return url, ref.author.display_name

        # 2. The command message itself
        url = _img_url(ctx.message)
        if url:
            return url, ctx.author.display_name

        # 3. Recent channel history
        async for msg in ctx.channel.history(limit=20, before=ctx.message):
            url = _img_url(msg)
            if url:
                return url, msg.author.display_name

        return None

    # ── Name generation ────────────────────────────────────────────────────────

    async def _generate_name(self, sender: str, raw: bytes) -> str:
        """Ask Claude (with vision) for a sticker name based on sender + image subject."""
        if not self.ai:
            return _sanitize_name(sender)
        try:
            loop  = asyncio.get_running_loop()
            thumb = await loop.run_in_executor(None, _make_thumb, raw)
            resp  = await asyncio.wait_for(
                self.ai.messages.create(
                    model=MODEL,
                    max_tokens=20,
                    messages=[{
                        "role": "user",
                        "content": [
                            {
                                "type": "image",
                                "source": {
                                    "type": "base64",
                                    "media_type": "image/jpeg",
                                    "data": base64.standard_b64encode(thumb).decode(),
                                },
                            },
                            {
                                "type": "text",
                                "text": (
                                    f"Make a funny Discord sticker name. "
                                    f"The sender is called '{sender}'. "
                                    "Look at the image — describe what the subject is doing or expressing "
                                    "in 1-2 words, then pair it with the sender's name. "
                                    "Keep it under 25 chars, lowercase, playful — like 'maddie shocked', "
                                    "'zach lmao', 'cat judging you', 'jake asleep'. "
                                    "Only letters, numbers, spaces. Reply with ONLY the name."
                                ),
                            },
                        ],
                    }],
                ),
                timeout=15,
            )
            text = getattr(resp.content[0], "text", "") or ""
            return _sanitize_name(text.strip())
        except Exception as e:
            log.warning("Sticker name generation failed: %s", e)
            return _sanitize_name(sender)

    # ── Command ────────────────────────────────────────────────────────────────

    @commands.hybrid_command(
        name="sticker",
        brief="Create a guild sticker from an image",
        help=(
            "Creates a guild sticker from an image.\n\n"
            "Reply to a message that has an image, or the bot will use\n"
            "the most recently sent image in the channel.\n\n"
            "Usage:\n"
            "  !sticker              — auto-generate name from sender\n"
            "  !sticker funny name   — use a specific name\n\n"
            "Requires Manage Emojis & Stickers permission."
        ),
    )
    @commands.guild_only()
    @commands.has_guild_permissions(manage_emojis_and_stickers=True)
    @commands.bot_has_guild_permissions(manage_emojis_and_stickers=True)
    async def sticker(self, ctx: commands.Context, *, name: str = ""):
        if not _PIL:
            await ctx.send("❌ Pillow is not installed. Run `pip install Pillow` in the bot venv.")
            return

        async with ctx.typing():
            result = await self._find_image(ctx)
            if not result:
                await ctx.send("❌ No image found. Reply to a message with an image, or send one recently.")
                return
            img_url, sender = result

            try:
                async with aiohttp.ClientSession() as session:
                    async with session.get(img_url, timeout=aiohttp.ClientTimeout(total=20)) as r:
                        raw = await r.read()
            except Exception as e:
                await ctx.send(f"❌ Failed to download image: {e}")
                return

            sticker_name = _sanitize_name(name) if name.strip() else await self._generate_name(sender, raw)

            try:
                loop      = asyncio.get_running_loop()
                processed = await loop.run_in_executor(None, _process_image, raw)
            except Exception as e:
                await ctx.send(f"❌ Image processing failed: {e}")
                return

            is_jpeg  = processed[:2] == b"\xff\xd8"
            filename = "sticker.jpg" if is_jpeg else "sticker.png"

            assert ctx.guild is not None  # guaranteed by @guild_only()
            try:
                sticker = await ctx.guild.create_sticker(
                    name=sticker_name,
                    description=f"Made by {ctx.author.display_name}",
                    emoji="🎭",
                    file=discord.File(io.BytesIO(processed), filename=filename),
                    reason=f"!sticker by {ctx.author} ({ctx.author.id})",
                )
                method = "subject zoom" if _CV2 else "center crop"
                await ctx.send(f"✅ **{sticker.name}** ({method})", stickers=[sticker])
            except discord.Forbidden:
                await ctx.send("❌ I don't have permission to create stickers here.")
            except discord.HTTPException as e:
                if "maximum" in str(e).lower():
                    await ctx.send("❌ This server has reached its sticker limit.")
                else:
                    await ctx.send(f"❌ Discord rejected the sticker: {e}")

    @sticker.error
    async def sticker_error(self, ctx: commands.Context, error):
        if isinstance(error, commands.MissingPermissions):
            await ctx.send("❌ You need **Manage Emojis & Stickers** permission to use this.")
        elif isinstance(error, commands.BotMissingPermissions):
            await ctx.send("❌ I need **Manage Emojis & Stickers** permission to create stickers.")


async def setup(bot: commands.Bot):
    await bot.add_cog(AutoStickerCog(bot))
