"""
auto_sticker.py — Create guild stickers from images with AI subject cropping.

Usage:
  !sticker              — use image from reply (or last image in channel)
  !sticker funny name   — same but override the generated name

Subject is auto-cropped using rembg (background removal ML model) if installed,
with a fallback to center-square crop. Sticker name is generated by Claude based
on the image sender's display name (e.g. "maddie shocked", "zach lmao").

Requirements (install in bot venv):
  pip install Pillow
  pip install rembg        (optional but highly recommended for photos of people)
"""

import asyncio
import io
import logging
import os
import re

import discord
from discord.ext import commands

try:
    import aiohttp as _aiohttp
    _AIOHTTP = True
except ImportError:
    _AIOHTTP = False

try:
    from PIL import Image as _Image
    _PIL = True
except ImportError:
    _PIL = False

try:
    from rembg import remove as _rembg_remove
    _REMBG = True
except ImportError:
    _REMBG = False

try:
    from anthropic import AsyncAnthropic as _Anthropic
except ImportError:
    _Anthropic = None

log = logging.getLogger(__name__)

MODEL        = "claude-haiku-4-5-20251001"
STICKER_SIZE = 320
MAX_BYTES    = 490 * 1024    # 490KB — stay under Discord's 500KB limit
_NAME_RE     = re.compile(r"[^a-zA-Z0-9 _\-]")


def _sanitize_name(name: str) -> str:
    name = _NAME_RE.sub("", name).strip()[:30]
    return name if len(name) >= 2 else "sticker"


def _process_image(raw: bytes) -> bytes:
    """
    Convert raw image bytes → 320×320 sticker PNG.
    Uses rembg for background removal if available, otherwise center-square crop.
    """
    if not _PIL:
        raise RuntimeError("Pillow not installed — run: pip install Pillow")

    if _REMBG:
        # Remove background; result is transparent RGBA PNG bytes
        processed = _rembg_remove(raw)
        img = _Image.open(io.BytesIO(processed)).convert("RGBA")
        # Trim transparent margins so the subject fills the frame
        bbox = img.getbbox()
        if bbox:
            img = img.crop(bbox)
    else:
        # Fallback: center-square crop (works okay for centered subjects)
        img = _Image.open(io.BytesIO(raw)).convert("RGBA")
        w, h = img.size
        side = min(w, h)
        left, top = (w - side) // 2, (h - side) // 2
        img = img.crop((left, top, left + side, top + side))

    # Scale to fit within 320×320, preserving aspect ratio
    img.thumbnail((STICKER_SIZE, STICKER_SIZE), _Image.LANCZOS)

    # Paste centred on a transparent 320×320 canvas
    canvas = _Image.new("RGBA", (STICKER_SIZE, STICKER_SIZE), (0, 0, 0, 0))
    ox = (STICKER_SIZE - img.width)  // 2
    oy = (STICKER_SIZE - img.height) // 2
    canvas.paste(img, (ox, oy), mask=img if img.mode == "RGBA" else None)

    # Save as optimised PNG
    out = io.BytesIO()
    canvas.save(out, format="PNG", optimize=True)

    # If still over limit, resize canvas down and re-pad (rare)
    if out.tell() > MAX_BYTES:
        shrink = int(STICKER_SIZE * 0.8)
        canvas = canvas.resize((shrink, shrink), _Image.LANCZOS)
        final  = _Image.new("RGBA", (STICKER_SIZE, STICKER_SIZE), (0, 0, 0, 0))
        final.paste(canvas, ((STICKER_SIZE - shrink) // 2, (STICKER_SIZE - shrink) // 2))
        out = io.BytesIO()
        final.save(out, format="PNG", optimize=True)

    out.seek(0)
    return out.read()


class AutoStickerCog(commands.Cog, name="AutoSticker"):
    """Creates guild stickers from images with AI subject isolation and name generation."""

    def __init__(self, bot: commands.Bot):
        self.bot = bot
        api_key  = os.getenv("ANTHROPIC_API_KEY")
        self.ai  = _Anthropic(api_key=api_key) if _Anthropic and api_key else None

    def cog_load(self):
        log.info("Cog Loaded. rembg=%s Pillow=%s", _REMBG, _PIL)
        if not _PIL:
            log.warning("Pillow not installed — !sticker will fail. Run: pip install Pillow")
        if not _REMBG:
            log.info("rembg not installed — using center-crop fallback. Run: pip install rembg")

    def cog_unload(self):
        log.info("Cog Unloaded.")

    # ── Image discovery ────────────────────────────────────────────────────────

    async def _find_image(self, ctx: commands.Context) -> tuple[str, str] | None:
        """
        Return (image_url, sender_display_name) or None.
        Checks: reply → command message attachments → last 20 channel messages.
        """
        def _img_url(msg: discord.Message) -> str | None:
            for att in msg.attachments:
                if att.content_type and att.content_type.startswith("image"):
                    return att.url
            for emb in msg.embeds:
                if emb.image:
                    return emb.image.url
                if emb.thumbnail:
                    return emb.thumbnail.url
            return None

        # 1. Replied-to message
        if ctx.message.reference and ctx.message.reference.resolved:
            ref = ctx.message.reference.resolved
            if isinstance(ref, discord.Message):
                url = _img_url(ref)
                if url:
                    return url, ref.author.display_name

        # 2. The command message itself (user attached an image with the command)
        url = _img_url(ctx.message)
        if url:
            return url, ctx.author.display_name

        # 3. Recent channel history
        async for msg in ctx.channel.history(limit=20, before=ctx.message):
            url = _img_url(msg)
            if url:
                return url, msg.author.display_name

        return None

    # ── Name generation ────────────────────────────────────────────────────────

    async def _generate_name(self, sender: str) -> str:
        """Ask Claude for a short, punchy sticker name based on the sender's name."""
        if not self.ai:
            return _sanitize_name(sender)
        try:
            resp = await asyncio.wait_for(
                self.ai.messages.create(
                    model=MODEL,
                    max_tokens=20,
                    messages=[{
                        "role": "user",
                        "content": (
                            f"Make a funny Discord sticker name for someone called '{sender}'. "
                            "Keep it short (under 25 chars), lowercase, playful — like 'maddie shocked' "
                            "or 'jake lmao' or 'zach vibing'. "
                            "Only letters, numbers, spaces. Reply with ONLY the name."
                        ),
                    }],
                ),
                timeout=10,
            )
            return _sanitize_name(resp.content[0].text.strip())
        except Exception as e:
            log.warning("Sticker name generation failed: %s", e)
            return _sanitize_name(sender)

    # ── Command ────────────────────────────────────────────────────────────────

    @commands.command(
        name="sticker",
        brief="Create a guild sticker from an image",
        help=(
            "Creates a guild sticker from an image.\n\n"
            "Reply to a message that has an image, or the bot will use\n"
            "the most recently sent image in the channel.\n\n"
            "Usage:\n"
            "  !sticker              — auto-generate name from sender\n"
            "  !sticker funny name   — use a specific name\n\n"
            "Requires Manage Emojis & Stickers permission."
        ),
    )
    @commands.guild_only()
    @commands.has_guild_permissions(manage_emojis_and_stickers=True)
    @commands.bot_has_guild_permissions(manage_emojis_and_stickers=True)
    async def sticker(self, ctx: commands.Context, *, name: str = ""):
        if not _PIL:
            await ctx.send("❌ Pillow is not installed. Run `pip install Pillow` in the bot venv.")
            return

        async with ctx.typing():
            # Find image
            result = await self._find_image(ctx)
            if not result:
                await ctx.send("❌ No image found. Reply to a message with an image, or send one recently.")
                return
            img_url, sender = result

            # Determine sticker name
            sticker_name = _sanitize_name(name) if name.strip() else await self._generate_name(sender)

            # Download image
            try:
                async with _aiohttp.ClientSession() as session:
                    async with session.get(img_url, timeout=_aiohttp.ClientTimeout(total=20)) as r:
                        raw = await r.read()
            except Exception as e:
                await ctx.send(f"❌ Failed to download image: {e}")
                return

            # Process (CPU-bound — run in executor)
            try:
                loop      = asyncio.get_running_loop()
                processed = await loop.run_in_executor(None, _process_image, raw)
            except Exception as e:
                await ctx.send(f"❌ Image processing failed: {e}")
                return

            # Upload sticker
            try:
                sticker = await ctx.guild.create_sticker(
                    name=sticker_name,
                    description=f"Made by {ctx.author.display_name}",
                    emoji="🎭",
                    file=discord.File(io.BytesIO(processed), filename="sticker.png"),
                    reason=f"!sticker by {ctx.author} ({ctx.author.id})",
                )
                method = "rembg cutout" if _REMBG else "center crop"
                await ctx.send(f"✅ Sticker **{sticker.name}** created! ({method})")
            except discord.Forbidden:
                await ctx.send("❌ I don't have permission to create stickers here.")
            except discord.HTTPException as e:
                if "maximum" in str(e).lower():
                    await ctx.send("❌ This server has reached its sticker limit.")
                else:
                    await ctx.send(f"❌ Discord rejected the sticker: {e}")

    @sticker.error
    async def sticker_error(self, ctx: commands.Context, error):
        if isinstance(error, commands.MissingPermissions):
            await ctx.send("❌ You need **Manage Emojis & Stickers** permission to use this.")
        elif isinstance(error, commands.BotMissingPermissions):
            await ctx.send("❌ I need **Manage Emojis & Stickers** permission to create stickers.")


async def setup(bot: commands.Bot):
    await bot.add_cog(AutoStickerCog(bot))
